### ISSUE TITLE
create() method's second parameter when using AMD modules

### ISSUE THREAD

**Issue by johngrimsey** [philmander/inverted#13]
Hi there, love this library thanks so much. Unless I've missed something in the docs it seems the create() method requires the second parameter. I am using AMD modules so can't quite work out what it should be, inverted turns its nose up without a value so I just pass in an arbitrary string for now. This doesn't feel right! What should I be doing?
Cheers
John

**Comment by philmander** [comment]
Hi John, 

Its actually been a while since I worked on this project. But I can't see why you would need the second param if using AMD modules. Its only required for loading common js modules and the amd based unit tests run happily without it (https://github.com/philmander/inverted/blob/master/test/integration-tests.html)

What is actually happening, if you omit the second param?
